runtime: python310
entrypoint: gunicorn -b :$PORT server.main:app

instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 2

handlers:
  # Handle CORS preflight requests
  - url: /.*
    script: auto
    secure: always
    redirect_http_response_code: 301

# Since App Engine's yaml doesn't support CORS headers directly for script handlers,
# we'll need to handle CORS in the Flask application

env_variables:
  PORT: 8080
  DB_HOST: /cloudsql/jaybird-connect:us-east1:jaybird-db
  DB_NAME: sonomas_menu
  DB_USER: postgres
  DB_PASSWORD: bagels4life
  FLASK_ENV: "production"
  JWT_SECRET: "49d83126fae6cd7e8f3575e06c89c2ddb34f2bcd34cba4af8cc48009f074f8fd"
  SMTP_SERVER: smtp.gmail.com
  SMTP_PORT: 587
  SMTP_USERNAME: info@byjaybird.com
  SMTP_PASSWORD: bagels4life
  SMTP_FROM_EMAIL: info@byjaybird.com

beta_settings:
  cloud_sql_instances: jaybird-connect:us-east1:jaybird-db