name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.GCP_OIDC_PROVIDER }}
          service_account: ${{ secrets.GCP_OIDC_SERVICE_ACCOUNT }}

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: '>= 363.0.0'

      - name: Verify auth and env
        run: |
          gcloud projects describe jaybird-connect
          gcloud info

      - name: Deploy to App Engine (Standard)
        run: gcloud app deploy app.yaml --quiet --project=jaybird-connect --no-cache

      - name: Show debug info on failure
        if: failure()
        run: |
          echo "::error:: Deployment failed, printing gcloud info:"
          gcloud config list
          gcloud auth list
          gcloud info
